language: objective-c
osx_image: xcode8.3
script:
    - xcodebuild clean test -project ScannerMaster.xcodeproj -scheme ScannerMaster -destination "platform=iOS Simulator,name=iPhone 7,OS=10.0" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet